#!/usr/bin/env python3
"""Generate src/fd_metrics.h (character widths of the standard PDF/PostScript
fonts used by fugdraw) from the Adobe Core 14 AFM files.

Usage: python3 tools/gen_metrics.py /path/to/pdfcorefonts > src/fd_metrics.h

The AFM files (and their readme.txt, whose license allows this use) are
distributed, for instance, with matplotlib in mpl-data/fonts/pdfcorefonts.
Text fonts use ISO Latin-1 (= PDF WinAnsiEncoding for codes 32-126 and
160-255); Symbol uses its built-in encoding.
"""
import os
import sys

FONTS = ["Helvetica", "Helvetica-Bold", "Times-Roman", "Times-Italic", "Symbol"]

ASCII = ("space exclam quotedbl numbersign dollar percent ampersand quotesingle "
         "parenleft parenright asterisk plus comma hyphen period slash zero one "
         "two three four five six seven eight nine colon semicolon less equal "
         "greater question at A B C D E F G H I J K L M N O P Q R S T U V W X Y Z "
         "bracketleft backslash bracketright asciicircum underscore grave a b c d "
         "e f g h i j k l m n o p q r s t u v w x y z braceleft bar braceright "
         "asciitilde").split()
LATIN1 = ("space exclamdown cent sterling currency yen brokenbar section dieresis "
          "copyright ordfeminine guillemotleft logicalnot hyphen registered macron "
          "degree plusminus twosuperior threesuperior acute mu paragraph "
          "periodcentered cedilla onesuperior ordmasculine guillemotright "
          "onequarter onehalf threequarters questiondown Agrave Aacute Acircumflex "
          "Atilde Adieresis Aring AE Ccedilla Egrave Eacute Ecircumflex Edieresis "
          "Igrave Iacute Icircumflex Idieresis Eth Ntilde Ograve Oacute Ocircumflex "
          "Otilde Odieresis multiply Oslash Ugrave Uacute Ucircumflex Udieresis "
          "Yacute Thorn germandbls agrave aacute acircumflex atilde adieresis aring "
          "ae ccedilla egrave eacute ecircumflex edieresis igrave iacute icircumflex "
          "idieresis eth ntilde ograve oacute ocircumflex otilde odieresis divide "
          "oslash ugrave uacute ucircumflex udieresis yacute thorn ydieresis").split()
assert len(ASCII) == 95 and len(LATIN1) == 96


def read_afm(path):
    by_name, by_code, info = {}, {}, {}
    for line in open(path, encoding="latin-1"):
        if line.startswith("C "):
            fields = dict(f.strip().split(" ", 1) for f in line.split(";") if f.strip())
            code, wx, name = int(fields["C"]), int(fields["WX"]), fields["N"]
            by_name[name] = wx
            if code >= 0:
                by_code[code] = wx
        else:
            key = line.split(" ", 1)[0]
            if key in ("CapHeight", "XHeight", "Ascender", "Descender"):
                info[key] = int(line.split()[1])
    return by_name, by_code, info


def main():
    folder = sys.argv[1]
    print("/* fd_metrics.h - generated by tools/gen_metrics.py: do not edit.")
    print(" *")
    print(" * Character widths (1/1000 em) of the standard PDF/PostScript fonts,")
    print(" * derived (modified) from the Adobe Core 14 AFM files:")
    for font in FONTS:
        line = open(os.path.join(folder, font + ".afm"), encoding="latin-1").readlines()[1]
        print(" *   %s: %s" % (font, line.replace("Comment ", "").strip()))
    print(" *")
    text = open(os.path.join(folder, "readme.txt"), encoding="latin-1").read()
    start = text.index("This file and the 14")
    for line in text[start:].strip().splitlines():
        print(" * " + line.rstrip())
    print(" */")
    print()
    print("#ifndef FD_METRICS_H\n#define FD_METRICS_H\n")
    print("#define FD_NFONTS %d\n" % len(FONTS))
    print("static const char *fd_font_names[FD_NFONTS] = {")
    print("   " + ", ".join('"%s"' % f for f in FONTS) + " };\n")
    infos = []
    print("/* widths of codes 0..255 (0 = no glyph) */")
    print("static const short fd_widths[FD_NFONTS][256] = {")
    for font in FONTS:
        by_name, by_code, info = read_afm(os.path.join(folder, font + ".afm"))
        infos.append(info)
        widths = [0] * 256
        if font == "Symbol":
            for code, wx in by_code.items():
                widths[code] = wx
        else:
            for i, name in enumerate(ASCII):
                widths[32 + i] = by_name.get(name, 0)
            for i, name in enumerate(LATIN1):
                widths[160 + i] = by_name.get(name, 0)
        print("  { /* %s */" % font)
        for row in range(0, 256, 16):
            print("    " + ", ".join("%4d" % w for w in widths[row:row + 16]) + ",")
        print("  },")
    print("};\n")
    print("/* x-height and cap height (1/1000 em) */")
    print("static const short fd_xheight[FD_NFONTS] = { %s };" %
          ", ".join(str(i.get("XHeight", 500)) for i in infos))
    print("static const short fd_capheight[FD_NFONTS] = { %s };" %
          ", ".join(str(i.get("CapHeight", 700)) for i in infos))
    print("\n#endif")


main()
